import {
  SOL_PRAGMA,
  SPDX_LICENSE,
  protoNameToSol,
  codecLibName,
  protoFileToSolFile,
  relativeImportPath
} from "../util/names.js"
import { log } from "../util/logger.js"
import {
  FieldInfo,
  DecodeBranch,
  genStructMember,
  genFieldEncode,
  genFieldDecode,
  isRepeated
} from "./field.js"
import { resolveSolType } from "./type-map.js"
import { toSolFieldName, structNameToVarName } from "../util/names.js"

/**
 * Descriptor subset for a protobuf message needed by the codegen.
 */
export interface MessageDescriptor {
  /** Simple name (e.g. "MyMessage") */
  name: string
  /** Fully qualified name (e.g. ".my_package.MyMessage") */
  fullName: string
  /** Field descriptors */
  fields: FieldInfo[]
  /** Nested message descriptors (for map entry types, etc.) */
  nestedMessages: MessageDescriptor[]
  /** True if this message is a synthetic map entry */
  isMapEntry: boolean
}

/**
 * Registry mapping fully-qualified protobuf type names (e.g. ".sysio.opp.types.ChainId")
 * to the proto file and package that defines them.
 */
export type TypeRegistry = Map<string, { protoFile: string; package: string }>

/**
 * Generate a complete .sol file containing struct definitions and
 * encode/decode codec libraries for all non-map-entry messages
 * in a given proto file.
 */
export function generateSolFile(
  messages: MessageDescriptor[],
  protoFileName: string,
  runtimeImport: string,
  currentSolFile: string,
  typeRegistry: TypeRegistry
): string {
  const lines: string[] = []

  lines.push(`// SPDX-License-Identifier: ${SPDX_LICENSE}`)
  lines.push(`pragma solidity ${SOL_PRAGMA};`)
  lines.push(``)
  lines.push(`// Auto-generated by protoc-gen-solidity from ${protoFileName}`)
  lines.push(`// DO NOT EDIT`)
  lines.push(``)
  lines.push(`import {ProtobufRuntime} from "${runtimeImport}";`)

  // Emit cross-file imports for types defined in other proto files
  const externalDeps = resolveExternalImports(messages, protoFileName, typeRegistry)
  for (const [depSolFile, typeNames] of externalDeps) {
    const relPath = relativeImportPath(currentSolFile, depSolFile)
    const symbols = [...typeNames]
      .sort()
      .flatMap(t => [t, codecLibName(t)])
    lines.push(`import {${symbols.join(", ")}} from "${relPath}";`)
  }

  lines.push(``)

  // Generate structs first (forward declarations)
  for (const msg of messages) {
    if (msg.isMapEntry) continue
    lines.push(genStruct(msg))
    lines.push(``)
  }

  // Generate codec libraries
  for (const msg of messages) {
    if (msg.isMapEntry) continue
    lines.push(genCodecLibrary(msg))
    lines.push(``)
  }

  return lines.join("\n")
}

/**
 * Generate Solidity struct definition for a message.
 */
function genStruct(msg: MessageDescriptor): string {
  const name = protoNameToSol(msg.fullName)
  log.debug(`Generating struct ${name} (${msg.fields.length} fields)`)

  const members = msg.fields
    .filter(f => !isMapEntryField(f, msg))
    .map(f => {
      // If this field references a map entry, convert to parallel arrays
      const mapEntry = resolveMapEntry(f, msg)
      if (mapEntry) {
        return genStructMember({ ...f, mapEntry })
      }
      return genStructMember(f)
    })

  return [`struct ${name} {`, ...members, `}`].join("\n")
}

/**
 * Generate the codec library with encode() and decode() for a message.
 */
function genCodecLibrary(msg: MessageDescriptor): string {
  const structName = protoNameToSol(msg.fullName)
  const libName = codecLibName(structName)
  const varName = structNameToVarName(structName)

  log.debug(`Generating codec library ${libName}`)

  const encodeBody = genEncodeFunction(msg, structName, varName)
  const decodeBody = genDecodeFunction(msg, structName, varName)

  return [
    `library ${libName} {`,
    ``,
    encodeBody,
    ``,
    decodeBody,
    `}`
  ].join("\n")
}

/**
 * Generate the encode function body.
 */
function genEncodeFunction(
  msg: MessageDescriptor,
  structName: string,
  varName: string
): string {
  const lines: string[] = []
  lines.push(
    `  function encode(${structName} memory ${varName}) internal pure returns (bytes memory) {`
  )
  lines.push(`    bytes memory buf = "";`)

  for (const field of msg.fields) {
    if (isMapEntryField(field, msg)) continue

    const mapEntry = resolveMapEntry(field, msg)
    const fieldInfo = mapEntry ? { ...field, mapEntry } : field

    lines.push(``)
    lines.push(`    // field ${field.number}: ${field.name}`)
    lines.push(genFieldEncode(fieldInfo, varName))
  }

  lines.push(``)
  lines.push(`    return buf;`)
  lines.push(`  }`)
  return lines.join("\n")
}

/**
 * Info about a repeated/map field needed for the counting pre-pass.
 */
interface RepeatedFieldMeta {
  solName: string
  tag: number
  solType: string
  isMap: boolean
  mapKeyType?: string
  mapValType?: string
}

/**
 * Generate the decode function body with tag-dispatch loop.
 * Uses if/else-if chains (Solidity switch is only valid inside assembly).
 *
 * For messages with repeated or map fields, a counting pre-pass is emitted
 * first so that memory arrays can be allocated with the correct size
 * (Solidity does not support .push() on memory arrays).
 */
function genDecodeFunction(
  msg: MessageDescriptor,
  structName: string,
  varName: string
): string {
  const lines: string[] = []
  lines.push(
    `  function decode(bytes memory data) internal pure returns (${structName} memory ${varName}) {`
  )
  lines.push(`    uint256 pos = 0;`)
  lines.push(`    uint256 end = data.length;`)
  lines.push(``)

  // Collect field decode branches and repeated-field metadata
  const branches: DecodeBranch[] = []
  const repeated: RepeatedFieldMeta[] = []

  for (const field of msg.fields) {
    if (isMapEntryField(field, msg)) continue
    const mapEntry = resolveMapEntry(field, msg)
    const fieldInfo = mapEntry ? { ...field, mapEntry } : field
    const branch = genFieldDecode(fieldInfo, varName)
    branches.push(branch)

    if (isRepeated(field) || mapEntry) {
      const solName = toSolFieldName(field.name)
      const solType = resolveSolType(field.type, field.typeName)
      if (mapEntry) {
        const keyType = resolveSolType(mapEntry.keyType, undefined)
        const valType = resolveSolType(mapEntry.valueType, mapEntry.valueTypeName)
        repeated.push({ solName, tag: branch.tag, solType, isMap: true, mapKeyType: keyType, mapValType: valType })
      } else {
        repeated.push({ solName, tag: branch.tag, solType, isMap: false })
      }
    }
  }

  // Counting pre-pass for repeated/map fields
  if (repeated.length > 0) {
    for (const ri of repeated) {
      lines.push(`    uint256 _count_${ri.solName} = 0;`)
    }
    lines.push(`    {`)
    lines.push(`      uint256 _pos = 0;`)
    lines.push(`      while (_pos < end) {`)
    lines.push(`        uint64 _tag;`)
    lines.push(`        (_tag, _pos) = ProtobufRuntime._decode_key(data, _pos);`)
    for (const ri of repeated) {
      lines.push(`        if (_tag == ${ri.tag}) { _count_${ri.solName}++; }`)
    }
    lines.push(`        _pos = ProtobufRuntime._skip_field(data, _pos, _tag & 0x07);`)
    lines.push(`      }`)
    lines.push(`    }`)

    // Allocate arrays
    for (const ri of repeated) {
      if (ri.isMap) {
        lines.push(`    ${varName}.${ri.solName}_keys = new ${ri.mapKeyType!}[](_count_${ri.solName});`)
        lines.push(`    ${varName}.${ri.solName}_values = new ${ri.mapValType!}[](_count_${ri.solName});`)
      } else {
        lines.push(`    ${varName}.${ri.solName} = new ${ri.solType}[](_count_${ri.solName});`)
      }
    }

    // Index counters
    for (const ri of repeated) {
      lines.push(`    uint256 _idx_${ri.solName} = 0;`)
    }
    lines.push(``)
  }

  // Main decode loop
  lines.push(`    while (pos < end) {`)
  lines.push(`      uint64 tag;`)
  lines.push(`      (tag, pos) = ProtobufRuntime._decode_key(data, pos);`)
  lines.push(``)

  if (branches.length > 0) {
    for (let i = 0; i < branches.length; i++) {
      const { tag, body } = branches[i]
      const keyword = i === 0 ? "if" : "} else if"
      lines.push(`      ${keyword} (tag == ${tag}) {`)
      lines.push(body)
    }
    lines.push(`      } else {`)
  } else {
    lines.push(`      {`)
  }

  lines.push(
    `        pos = ProtobufRuntime._skip_field(data, pos, tag & 0x07);`
  )
  lines.push(`      }`)
  lines.push(`    }`)
  lines.push(`  }`)
  return lines.join("\n")
}

// ── Map entry resolution ──────────────────────────────────────────────

interface MapEntryInfo {
  keyType: number
  valueType: number
  valueTypeName?: string
}

/**
 * Check if a field references a map entry message type.
 */
function isMapEntryField(
  field: FieldInfo,
  parentMsg: MessageDescriptor
): boolean {
  if (field.type !== 11 || field.label !== 3) return false
  const nested = parentMsg.nestedMessages.find(
    m => field.typeName?.endsWith(`.${m.name}`)
  )
  return nested?.isMapEntry ?? false
}

/**
 * Resolve a map entry's key/value types from the synthetic nested message.
 */
function resolveMapEntry(
  field: FieldInfo,
  parentMsg: MessageDescriptor
): MapEntryInfo | undefined {
  if (field.type !== 11 || field.label !== 3) return undefined
  const nested = parentMsg.nestedMessages.find(
    m => field.typeName?.endsWith(`.${m.name}`)
  )
  if (!nested?.isMapEntry) return undefined

  const keyField = nested.fields.find(f => f.number === 1)
  const valField = nested.fields.find(f => f.number === 2)
  if (!keyField || !valField) return undefined

  return {
    keyType: keyField.type,
    valueType: valField.type,
    valueTypeName: valField.typeName
  }
}

/**
 * Find message-type fields that reference types defined in other proto files.
 * Returns a map from dependency .sol file path → set of type names to import.
 */
function resolveExternalImports(
  messages: MessageDescriptor[],
  currentProtoFile: string,
  typeRegistry: TypeRegistry
): Map<string, Set<string>> {
  const deps = new Map<string, Set<string>>()

  function addDep(typeName: string) {
    const entry = typeRegistry.get(typeName)
    if (!entry || entry.protoFile === currentProtoFile) return
    const depSolFile = protoFileToSolFile(entry.protoFile, entry.package)
    const solTypeName = protoNameToSol(typeName)
    if (!deps.has(depSolFile)) deps.set(depSolFile, new Set())
    deps.get(depSolFile)!.add(solTypeName)
  }

  for (const msg of messages) {
    if (msg.isMapEntry) continue
    for (const field of msg.fields) {
      if (field.type !== 11 || !field.typeName) continue

      // Check if this is a map entry reference
      const nested = msg.nestedMessages.find(
        m => field.typeName?.endsWith(`.${m.name}`)
      )
      if (nested?.isMapEntry) {
        // For map entries, check the value type for external deps
        const valField = nested.fields.find(f => f.number === 2)
        if (valField && valField.type === 11 && valField.typeName) {
          addDep(valField.typeName)
        }
        continue
      }

      addDep(field.typeName)
    }
  }

  return deps
}
